collections:
  - name: "niveles"
    label: "Niveles Educativos"
    folder: "content/niveles"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Título", widget: "string" }
      - { name: "description", label: "Descripción", widget: "text" }
      - { name: "body", label: "Contenido", widget: "markdown" }
      - label: "Áreas de Desarrollo"
        name: "areasDesarrollo"
        widget: "list"
        fields:
          - { name: "icon", label: "Ícono", widget: "string" }
          - { name: "title", label: "Título", widget: "string" }
          - { name: "description", label: "Descripción", widget: "text" }
          - { name: "color", label: "Color", widget: "string" }
      - label: "Actividades Diarias"
        name: "actividadesDiarias"
        widget: "list"
        fields:
          - { name: "hora", label: "Hora", widget: "string" }
          - { name: "actividad", label: "Actividad", widget: "string" }
          - { name: "emoji", label: "Emoji", widget: "string" }
      - label: "Habilidades"
        name: "habilidades"
        widget: "list"
        field: { name: "habilidad", label: "Habilidad", widget: "string" }
