
backend:
  name: git-gateway
  branch: main        # rama donde Netlify hará los commits


media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "niveles"
    label: "Niveles Educativos"
    folder: "content/niveles"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Título", widget: "string" }
      - { name: "description", label: "Descripción", widget: "text" }
      - { name: "body", label: "Contenido", widget: "markdown" }
